---
name: "Pull Request Checklist"
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
  workflow_dispatch:
jobs:
  pr_checklist:
    runs-on: ubuntu-latest
    name: Verify
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Action
        id: checklist
        uses: ceph/ceph-pr-checklist-action@8f595a7ed6d52b16f3d9f57027fcfbb786a8cf8d
